name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get cargo version
      id: cargo-version
      run: |
        echo "::set-output name=cargo-version::$(cargo -V)"

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ steps.cargo-version.cargo-version }}

    - name: update
      run: cargo update
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
